/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task;

import com.sun.glass.events.KeyEvent;
import gestionbd.GestionBD;
import java.awt.LayoutManager;
import java.util.Arrays;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import principal.Login;

/**
 *
 * @author jotac
 */
public class Task extends javax.swing.JFrame {

    String Usuario = Login.usuario;
    GestionBD gbd = new GestionBD();
    
    public Task() {
        initComponents();
        
        //Muestra tareas en la tabla
        gbd.muestraTareas(tablaTareas, Usuario);
        txtUsuario.setText("Usuario: " + Usuario);
               
//        Panel p = new Panel();
//        Panel p2 = new Panel();
//        jTabbedPane1.add("otro",p.agregaComponentes());
//
//        jTabbedPane1.add("otro2",p2.agregaComponentes());
        
        txtUsuario.setText("Usuario: " + Usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tareasPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTareas = new javax.swing.JTable();
        btnNuevaTarea = new javax.swing.JButton();
        TareasCompPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTareas1 = new javax.swing.JTable();
        btnNuevaTarea1 = new javax.swing.JButton();
        EstadisticaPanel = new javax.swing.JPanel();
        btnNuevaTarea2 = new javax.swing.JButton();
        OpcionesPanel = new javax.swing.JPanel();
        btnNuevaTarea3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(42, 43, 74));
        jPanel1.setForeground(new java.awt.Color(42, 43, 74));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 127, 39));
        jLabel1.setText("Menu Tareas");

        jTabbedPane1.setBackground(new java.awt.Color(42, 43, 74));
        jTabbedPane1.setForeground(new java.awt.Color(255, 127, 39));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tareasPanel.setBackground(new java.awt.Color(42, 43, 74));
        tareasPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 127, 39)));
        tareasPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tablaTareas.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, "", null, "", null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, "", null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Tarea", "Prioridad", "Tipo", "Descripcion", "Inicio", "% Completado", "Estado"
            }
        ));
        tablaTareas.setRowHeight(25);
        tablaTareas.setSelectionBackground(new java.awt.Color(255, 127, 39));
        tablaTareas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaTareasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTareas);

        btnNuevaTarea.setText("Nueva Tarea");
        btnNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaTareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tareasPanelLayout = new javax.swing.GroupLayout(tareasPanel);
        tareasPanel.setLayout(tareasPanelLayout);
        tareasPanelLayout.setHorizontalGroup(
            tareasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tareasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tareasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                    .addGroup(tareasPanelLayout.createSequentialGroup()
                        .addComponent(btnNuevaTarea)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tareasPanelLayout.setVerticalGroup(
            tareasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tareasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevaTarea)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tareas", tareasPanel);

        TareasCompPanel.setBackground(new java.awt.Color(51, 51, 51));
        TareasCompPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tablaTareas1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tablaTareas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "3", "4", null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° Tarea", "Descripcion", "Prioridad", "% Completado", "Estado"
            }
        ));
        tablaTareas1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaTareas1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaTareas1);

        btnNuevaTarea1.setText("Nueva Tarea");

        javax.swing.GroupLayout TareasCompPanelLayout = new javax.swing.GroupLayout(TareasCompPanel);
        TareasCompPanel.setLayout(TareasCompPanelLayout);
        TareasCompPanelLayout.setHorizontalGroup(
            TareasCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TareasCompPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevaTarea1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TareasCompPanelLayout.setVerticalGroup(
            TareasCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TareasCompPanelLayout.createSequentialGroup()
                .addGroup(TareasCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TareasCompPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnNuevaTarea1))
                    .addGroup(TareasCompPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tareas Completadas", TareasCompPanel);

        EstadisticaPanel.setBackground(new java.awt.Color(51, 51, 51));
        EstadisticaPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnNuevaTarea2.setText("Nueva Tarea");

        javax.swing.GroupLayout EstadisticaPanelLayout = new javax.swing.GroupLayout(EstadisticaPanel);
        EstadisticaPanel.setLayout(EstadisticaPanelLayout);
        EstadisticaPanelLayout.setHorizontalGroup(
            EstadisticaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadisticaPanelLayout.createSequentialGroup()
                .addGap(753, 753, 753)
                .addComponent(btnNuevaTarea2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EstadisticaPanelLayout.setVerticalGroup(
            EstadisticaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadisticaPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnNuevaTarea2)
                .addContainerGap(429, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estadistica", EstadisticaPanel);

        OpcionesPanel.setBackground(new java.awt.Color(51, 51, 51));
        OpcionesPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnNuevaTarea3.setText("Nueva Tarea");

        javax.swing.GroupLayout OpcionesPanelLayout = new javax.swing.GroupLayout(OpcionesPanel);
        OpcionesPanel.setLayout(OpcionesPanelLayout);
        OpcionesPanelLayout.setHorizontalGroup(
            OpcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesPanelLayout.createSequentialGroup()
                .addGap(753, 753, 753)
                .addComponent(btnNuevaTarea3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OpcionesPanelLayout.setVerticalGroup(
            OpcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnNuevaTarea3)
                .addContainerGap(429, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Opciones", OpcionesPanel);

        jButton2.setText("Nuevo Grupo ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 127, 39));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSoloPequeño.png"))); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 127, 39));
        txtUsuario.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsuario))
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1207, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        Panel p = new Panel();
//        jTabbedPane1.add("otro",p.agregaComponentes());
        
            //Codigo para conseguir valores seleccionados de la tabla
          DefaultTableModel modeloTabla =(DefaultTableModel) tablaTareas.getModel();
          String  nro_tarea = (String)modeloTabla.getValueAt(tablaTareas.getSelectedRow(),tablaTareas.getSelectedColumn());
          
          System.out.println(nro_tarea);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaTareaActionPerformed
       NuevaTarea nt = new NuevaTarea();
       nt.setVisible(true);
    }//GEN-LAST:event_btnNuevaTareaActionPerformed

    private void tablaTareasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaTareasKeyReleased

        //Codigo para detectar celdas modificadas en la tabla
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String  celdaModificada = (String)tablaTareas.getValueAt(tablaTareas.getSelectedRow(),tablaTareas.getSelectedColumn()).toString();
            System.out.println(celdaModificada);
        }
    }//GEN-LAST:event_tablaTareasKeyReleased

    private void tablaTareas1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaTareas1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaTareas1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EstadisticaPanel;
    private javax.swing.JPanel OpcionesPanel;
    private javax.swing.JPanel TareasCompPanel;
    private javax.swing.JButton btnNuevaTarea;
    private javax.swing.JButton btnNuevaTarea1;
    private javax.swing.JButton btnNuevaTarea2;
    private javax.swing.JButton btnNuevaTarea3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaTareas;
    private javax.swing.JTable tablaTareas1;
    private javax.swing.JPanel tareasPanel;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
