/*
 * The MIT License
 *
 * Copyright 2019 Juan Jimenez, Marco Avila.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package principal;

import funciones.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import gestionbd.*;
import javax.swing.JOptionPane;
import task.Task;


public class Login extends javax.swing.JFrame {

    boolean estadoVisble = false;
    GestionBD gbd = new GestionBD();
    
    //Variable global para pasar usuario
    public static String usuario;
    
    public Login() {
        initComponents();
        
        
        ImageIcon iconoApp = new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSolo.png"));
        this.setTitle("Calendar");
        this.setLocationRelativeTo(null);
        this.setIconImage(iconoApp.getImage());
        gbd.crearBD();
               
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfUsuario = new javax.swing.JTextField();
        txtfPasswd = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtRestablecer = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(42, 43, 74));
        jPanel1.setForeground(new java.awt.Color(42, 43, 74));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 127, 39));
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 127, 39));
        jLabel2.setText("Contraseña:");

        txtfUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfUsuario.setToolTipText("");
        txtfUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 127, 39)));
        txtfUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtfPasswd.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtfPasswd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfPasswd.setToolTipText("");
        txtfPasswd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 127, 39)));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calenderLogo2.png"))); // NOI18N

        jCheckBox1.setBackground(new java.awt.Color(42, 43, 74));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/visible1.png"))); // NOI18N
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        txtRestablecer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtRestablecer.setForeground(new java.awt.Color(255, 127, 39));
        txtRestablecer.setText("Restablecer contraseña...");
        txtRestablecer.setToolTipText("");
        txtRestablecer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtRestablecerMouseMoved(evt);
            }
        });
        txtRestablecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRestablecerMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRestablecerMouseExited(evt);
            }
        });

        btnRegistro.setBackground(new java.awt.Color(42, 43, 74));
        btnRegistro.setForeground(new java.awt.Color(255, 127, 39));
        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_user1.png"))); // NOI18N
        btnRegistro.setBorder(null);
        btnRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegistroMouseMoved(evt);
            }
        });
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroMouseExited(evt);
            }
        });
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(42, 43, 74));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login1.png"))); // NOI18N
        btnLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLoginMouseMoved(evt);
            }
        });
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1))
                            .addComponent(txtRestablecer))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRestablecer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRestablecerMouseMoved(MouseEvent evt) {//GEN-FIRST:event_txtRestablecerMouseMoved
        txtRestablecer.setForeground(Color.white);
    }//GEN-LAST:event_txtRestablecerMouseMoved

    private void txtRestablecerMouseExited(MouseEvent evt) {//GEN-FIRST:event_txtRestablecerMouseExited
        Color cp = new Color(255,127,39);
        txtRestablecer.setForeground(cp);
    }//GEN-LAST:event_txtRestablecerMouseExited

    private void jCheckBox1MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
       
        
       if(estadoVisble == false){
            jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hide1.png")));
            txtfPasswd.setEchoChar((char)0);
            estadoVisble = true;
            
       }else{
            jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/visible1.png")));
            txtfPasswd.setEchoChar('*');
            estadoVisble = false;
       }
       
     
        
        
       // jPasswordField1.setEchoChar('.');
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void btnRegistroActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
       
        RegistroUsuario rg = new RegistroUsuario();
        rg.setVisible(true);
       
    //Mail.sendEmail("juancarlos.jimenez@cliptecnologia.com");
       
       
        
        
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void jCheckBox1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

   
    private void btnRegistroMouseMoved(MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseMoved
       
       // btnRegistro.setIcon(new ImageIcon("src/iconos/add_user2.png"));
        Funciones.switchBtnIcon(getClass(),btnRegistro,"add_user",2);
        
        
    }//GEN-LAST:event_btnRegistroMouseMoved

    private void btnRegistroMouseExited(MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseExited
    //   btnRegistro.setIcon(new ImageIcon("src/iconos/add_user1.png"));
        Funciones.switchBtnIcon(getClass(),btnRegistro,"add_user",1);
    }//GEN-LAST:event_btnRegistroMouseExited

    private void btnLoginMouseExited(MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        Funciones.switchBtnIcon(getClass(), btnLogin, "login",1);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMouseMoved(MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseMoved
       Funciones.switchBtnIcon(getClass(), btnLogin, "login",2);
    }//GEN-LAST:event_btnLoginMouseMoved

    private void txtRestablecerMouseClicked(MouseEvent evt) {//GEN-FIRST:event_txtRestablecerMouseClicked
        RestablecerContrasena RS = new RestablecerContrasena();
    
        RS.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_txtRestablecerMouseClicked

    private void btnLoginActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        usuario = txtfUsuario.getText();
        String passwd = new String(txtfPasswd.getPassword());
        
        if(usuario.equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese un nombre de usuario","Mensaje", JOptionPane.OK_OPTION, new ImageIcon(getClass().getResource("/iconos/warning2.png")));
        }else{
            if(gbd.iniciaSesion(usuario, passwd)){
            Task task = new Task();
            task.setVisible(true);
            this.dispose();
            
        }
            
        }
            

       
        
      
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnLogin;
    javax.swing.JButton btnRegistro;
    javax.swing.JCheckBox jCheckBox1;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel4;
    javax.swing.JPanel jPanel1;
    javax.swing.JLabel txtRestablecer;
    javax.swing.JPasswordField txtfPasswd;
    javax.swing.JTextField txtfUsuario;
    // End of variables declaration//GEN-END:variables
}
