/*
 * The MIT License
 *
 * Copyright 2019 Juan Jimenez, Marco Avila.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package principal;
import funciones.*;
import gestionbd.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class RegistroUsuario extends javax.swing.JFrame {

     GestionBD gbd = new GestionBD();
     Boolean valida_u;
     Boolean valida_c;
    public RegistroUsuario() {
        initComponents();
        
        ImageIcon iconoApp = new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSolo.png"));
        this.setTitle("Calendar");
        this.setLocationRelativeTo(null);
        this.setIconImage(iconoApp.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfUsuario = new javax.swing.JTextField();
        txtfNombre = new javax.swing.JTextField();
        txtfPasswd = new javax.swing.JPasswordField();
        txtfConfirmarPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtfApellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtfEmail = new javax.swing.JTextField();
        txtValidaUser = new javax.swing.JLabel();
        txtValidaPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(42, 43, 74));
        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 127, 39));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit_user1.png"))); // NOI18N
        jLabel1.setText("Creacion de Usuario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 127, 39));
        jLabel2.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 127, 39));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 127, 39));
        jLabel5.setText("Confirmar Contraseña:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 127, 39));
        jLabel6.setText("Usuario:");

        txtfUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfUsuario.setToolTipText("");
        txtfUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 127, 39)));
        txtfUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtfUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfUsuarioFocusLost(evt);
            }
        });
        txtfUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtfUsuarioMouseReleased(evt);
            }
        });
        txtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfUsuarioActionPerformed(evt);
            }
        });

        txtfNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfNombre.setToolTipText("");
        txtfNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 127, 39)));
        txtfNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfNombreFocusGained(evt);
            }
        });

        txtfPasswd.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtfPasswd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfPasswd.setToolTipText("");
        txtfPasswd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 127, 39)));

        txtfConfirmarPass.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtfConfirmarPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfConfirmarPass.setToolTipText("");
        txtfConfirmarPass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 127, 39)));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSoloPequeño.png"))); // NOI18N

        btnAceptar.setBackground(new java.awt.Color(42, 43, 74));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login1.png"))); // NOI18N
        btnAceptar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAceptarMouseMoved(evt);
            }
        });
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 127, 39));
        jLabel8.setText("Apellido:");

        txtfApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfApellido.setToolTipText("");
        txtfApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 127, 39)));
        txtfApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 127, 39));
        jLabel9.setText("Direccion de Correo:");

        txtfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfEmail.setToolTipText("");
        txtfEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 127, 39)));
        txtfEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtValidaUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValidaUser.setForeground(new java.awt.Color(255, 127, 39));
        txtValidaUser.setText("...");
        txtValidaUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtValidaUserMouseMoved(evt);
            }
        });
        txtValidaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtValidaUserMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtValidaUserMouseReleased(evt);
            }
        });

        txtValidaPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValidaPass.setForeground(new java.awt.Color(255, 127, 39));
        txtValidaPass.setText("...");
        txtValidaPass.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtValidaPassMouseMoved(evt);
            }
        });
        txtValidaPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtValidaPassMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValidaPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfConfirmarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValidaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(127, 127, 127))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtValidaUser))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtfPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValidaPass))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtfConfirmarPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAceptar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseMoved
        Funciones.switchBtnIcon(getClass(), btnAceptar, "login",2);
    }//GEN-LAST:event_btnAceptarMouseMoved

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        Funciones.switchBtnIcon(getClass(), btnAceptar, "login",1);
    }//GEN-LAST:event_btnAceptarMouseExited

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
                
                ImageIcon warningIcon = new ImageIcon(getClass().getResource("/iconos/warning2.png"));               
                String usuario = txtfUsuario.getText();
                String nombre = txtfNombre.getText();
                String apellido = txtfApellido.getText();
                String email = txtfEmail.getText();
                String pass =  new String(txtfPasswd.getPassword());
                
                if(usuario.equals("")){
                    JOptionPane.showMessageDialog(null, "Ingrese un nombre de usuario","Alerta!",JOptionPane.ERROR,warningIcon);
                }
                
                String confirmPass = new String(txtfConfirmarPass.getPassword());
                valida_c =Funciones.validaContraseña(pass, confirmPass); 
                
                if(valida_c){
                    
                    gbd.CreaUsuario(usuario, nombre, apellido, email, pass);
                    this.dispose();
                    
                }else{
                    
                    Funciones.switchTxtIcon(getClass(), txtValidaPass, "warning", 1);
                    txtValidaPass.setToolTipText("Las contraseñas ingresadas no coinciden. Ingresar ambas contraseñas nuevamente");
                    txtValidaPass.setText("");
                    txtfPasswd.setText("");
                    txtfConfirmarPass.setText("");
                    
                
                    
                }
                     
                  
                    
                
                    
               
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtfUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfUsuarioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfUsuarioMouseReleased

    private void txtfUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfUsuarioFocusLost
        
           valida_u = gbd.validaUsuario(txtfUsuario.getText());
        
            if (valida_u == true){
                Funciones.switchTxtIcon(getClass(),txtValidaUser , "warning", 1);
                
                txtValidaUser.setToolTipText("Este nombre de usuario ya existe, por favor ingresar un nombre de usuario diferente");
                txtValidaUser.setText("");
                btnAceptar.setEnabled(false);
            
            }else  { 
               
                btnAceptar.setEnabled(true);
                Funciones.switchTxtIcon(getClass(),txtValidaUser , "checked_user", 1);
                
                txtValidaUser.setToolTipText("Nombre de usario correcto.");
                txtValidaUser.setText("");
            }
        
      
      
    }//GEN-LAST:event_txtfUsuarioFocusLost

    private void txtfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfNombreFocusGained
        
        
    }//GEN-LAST:event_txtfNombreFocusGained

    private void txtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfUsuarioActionPerformed

    private void txtValidaUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValidaUserMouseMoved
       if(txtValidaUser.getText() == "..."){
          txtValidaUser.setText("...");
      }else{
        if (valida_u){
           Funciones.switchTxtIcon(getClass(), txtValidaUser,"warning",2);
       }
       else{
            Funciones.switchTxtIcon(getClass(), txtValidaUser,"checked_user",2);
       }
       }
           
    }//GEN-LAST:event_txtValidaUserMouseMoved

    private void txtValidaUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValidaUserMouseReleased
            
       
    }//GEN-LAST:event_txtValidaUserMouseReleased

    private void txtValidaUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValidaUserMouseExited
      if(txtValidaUser.getText() == "..."){
          txtValidaUser.setText("...");
      }else{
        if (valida_u){
           Funciones.switchTxtIcon(getClass(), txtValidaUser,"warning",1);
       }
       else{
            Funciones.switchTxtIcon(getClass(), txtValidaUser,"checked_user",1);
       }
      }
         
    }//GEN-LAST:event_txtValidaUserMouseExited

    private void txtValidaPassMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValidaPassMouseMoved
        try{   
        if(txtValidaPass.getText().equals("..."))
           txtValidaPass.setText("...");
       else
           Funciones.switchTxtIcon(getClass(), txtValidaPass,"warning", 2);
        }
        catch(NullPointerException e){
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_txtValidaPassMouseMoved

    private void txtValidaPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValidaPassMouseExited
        try{   
        if(txtValidaPass.getText().equals("..."))
           txtValidaPass.setText("...");
       else
           Funciones.switchTxtIcon(getClass(), txtValidaPass,"warning", 1);
        }
        catch(NullPointerException e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_txtValidaPassMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtValidaPass;
    private javax.swing.JLabel txtValidaUser;
    private javax.swing.JTextField txtfApellido;
    private javax.swing.JPasswordField txtfConfirmarPass;
    private javax.swing.JTextField txtfEmail;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JPasswordField txtfPasswd;
    private javax.swing.JTextField txtfUsuario;
    // End of variables declaration//GEN-END:variables
}
